### ISSUE TITLE
Add Animation in Background

### ISSUE THREAD

**Issue by vinaytheprogrammer** [vinaytheprogrammer/Chitchat#5]
### **Expected Outcome**
Implement a smooth and visually appealing background animation.
Ensure the animation does not interfere with the content readability or overall user experience.
Make sure the animation is performance-optimized and does not cause lag or slow down the application.

### **Additional Requirements**
Use CSS animations or JavaScript libraries to achieve the desired effect.
Ensure compatibility with different browsers and devices.
Provide options to toggle the animation on and off for users who may prefer a static background.

### **Improvement Suggestions**
Open to suggestions for different types of animations (e.g., gradient transitions, particle effects, subtle patterns).
Feedback on any potential issues or improvements regarding the animation effect.

### **Additional Information**
Consider using libraries like anime.js, three.js, or pure CSS for implementing the animation.
Ensure the animation is accessible and does not cause discomfort to users with motion sensitivity.

**Comment by Milosavljevichh** [comment]
Hi, I'd like to work on this issue. I want to note that, following your Installation Instructions, I'm unable to generate an API key due to Google AI Studio not being available in my region.
However, as much as I can assume, that shouldn't cause trouble for this specific issue.
